package maingame.init;

import miscellaneous.WordTypes;
import java.util.HashMap;

public class RecognisableWords implements java.io.Serializable {   

    public static HashMap<String, WordTypes> vocab = new HashMap<>();
    
    public static void initVocab() {
        vocab.put("securitronmk5",WordTypes.NOUN);
        vocab.put("villager",WordTypes.NOUN);
        vocab.put("footlocker", WordTypes.NOUN);
        vocab.put("drawer", WordTypes.NOUN);
        vocab.put("vending", WordTypes.NOUN);
        vocab.put("machine", WordTypes.NOUN);
        vocab.put("safe", WordTypes.NOUN);
        vocab.put("chest", WordTypes.NOUN);
        vocab.put("cabinet", WordTypes.NOUN);
        vocab.put("box", WordTypes.NOUN);
        vocab.put("button", WordTypes.NOUN);
        vocab.put("card", WordTypes.NOUN);
        vocab.put("chair", WordTypes.NOUN);
        vocab.put("coin", WordTypes.NOUN);
        vocab.put("computer", WordTypes.NOUN);
        vocab.put("console", WordTypes.NOUN);
        vocab.put("cupboard", WordTypes.NOUN);
        vocab.put("garbage", WordTypes.ADJECTIVE);
        vocab.put("desk", WordTypes.NOUN);
        vocab.put("door", WordTypes.NOUN);
        vocab.put("key", WordTypes.NOUN);
        vocab.put("bin", WordTypes.NOUN);
        vocab.put("knife", WordTypes.NOUN);
        vocab.put("lamp", WordTypes.NOUN);
        vocab.put("lever", WordTypes.NOUN);
        vocab.put("lights", WordTypes.NOUN);
        vocab.put("ring", WordTypes.NOUN);
        vocab.put("screen", WordTypes.NOUN);
        vocab.put("sign", WordTypes.NOUN);
        vocab.put("slot", WordTypes.NOUN);
        vocab.put("table", WordTypes.NOUN);
        vocab.put("chip", WordTypes.NOUN);
        vocab.put("test", WordTypes.VERB);
        vocab.put("get", WordTypes.VERB);
        vocab.put("i", WordTypes.VERB);
        vocab.put("inventory", WordTypes.VERB);
        vocab.put("go", WordTypes.VERB);
        vocab.put("take", WordTypes.VERB);
        vocab.put("drop", WordTypes.VERB);
        vocab.put("put", WordTypes.VERB);
        vocab.put("l", WordTypes.VERB);
        vocab.put("look", WordTypes.VERB);
        vocab.put("lock", WordTypes.VERB);
        vocab.put("unlock", WordTypes.VERB);
        vocab.put("open", WordTypes.VERB);
        vocab.put("close", WordTypes.VERB);
        vocab.put("press", WordTypes.VERB);
        vocab.put("pull", WordTypes.VERB);
        vocab.put("push", WordTypes.VERB);
        vocab.put("talk",WordTypes.VERB);
        vocab.put("attack",WordTypes.VERB);
        vocab.put("n", WordTypes.VERB);
        vocab.put("s", WordTypes.VERB);
        vocab.put("w", WordTypes.VERB);
        vocab.put("e", WordTypes.VERB);
        vocab.put("up", WordTypes.VERB);
        vocab.put("u", WordTypes.VERB);
        vocab.put("down", WordTypes.VERB);
        vocab.put("north",WordTypes.VERB);
        vocab.put("south",WordTypes.VERB);
        vocab.put("west",WordTypes.VERB);
        vocab.put("east",WordTypes.VERB);
        vocab.put("d", WordTypes.VERB);
        vocab.put("q", WordTypes.VERB);
        vocab.put("quit", WordTypes.VERB);
        vocab.put("small", WordTypes.ADJECTIVE);
        vocab.put("tiny", WordTypes.ADJECTIVE);
        vocab.put("big", WordTypes.ADJECTIVE);
        vocab.put("cardboard", WordTypes.ADJECTIVE);
        vocab.put("display", WordTypes.ADJECTIVE);
        vocab.put("huge", WordTypes.ADJECTIVE);
        vocab.put("metal", WordTypes.ADJECTIVE);
        vocab.put("plastic", WordTypes.ADJECTIVE);
        vocab.put("spiky", WordTypes.ADJECTIVE);
        vocab.put("gold", WordTypes.ADJECTIVE);
        vocab.put("golden", WordTypes.ADJECTIVE);
        vocab.put("silver", WordTypes.ADJECTIVE);
        vocab.put("tall", WordTypes.ADJECTIVE);
        vocab.put("wooden", WordTypes.ADJECTIVE);
        vocab.put("micro", WordTypes.ADJECTIVE);
        vocab.put("mini", WordTypes.ADJECTIVE);
        vocab.put("shiny", WordTypes.ADJECTIVE);
        vocab.put("dirty", WordTypes.ADJECTIVE);
        vocab.put("a", WordTypes.ARTICLE);
        vocab.put("an", WordTypes.ARTICLE);
        vocab.put("some", WordTypes.ARTICLE);
        vocab.put("the", WordTypes.ARTICLE);
        vocab.put("in", WordTypes.PREPOSITION);
        vocab.put("into", WordTypes.PREPOSITION);
        vocab.put("to",WordTypes.PREPOSITION);
        vocab.put("at", WordTypes.PREPOSITION);        
        vocab.put("with", WordTypes.PREPOSITION);        
    }
}
